const { join } = require('path');

const test = require('ava');
const del = require('del');

const { compile, hashLiteral } = require('../helpers/unit');

const outputPath = join(__dirname, '../output/nameless-chunks');

test.after(() => del(outputPath));

test('add a literal mapping of files generated by nameless chunks.', async (t) => {
  const config = {
    context: __dirname,
    entry: {
      nameless: '../fixtures/nameless.js'
    },
    output: {
      filename: `[name].${hashLiteral}.js`,
      path: join(outputPath, 'nameless-chunks')
    }
  };

  const { manifest, stats } = await compile(config, t);

  t.is(Object.keys(manifest).length, 2);
  t.is(manifest['nameless.js'], `nameless.${stats.hash}.js`);
});
