// describe('nameless chunks', () => {
//   test('add a literal mapping of files generated by nameless chunks.', (done) => {
//     webpackCompile(
//       {
//         context: __dirname,
//         entry: {
//           nameless: './fixtures/nameless.js'
//         },
//         output: {
//           filename: '[name].[hash].js'
//         }
//       },
//       {},
//       (manifest, stats) => {
//         expect(Object.keys(manifest).length).toEqual(2);
//         expect(manifest['nameless.js']).toEqual(`nameless.${stats.hash}.js`);
//
//         done();
//       }
//     );
//   });
// });
