name: Windows

on:
  pull_request:
    types:
      - edited
      - opened
      - synchronize
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node: ['18']

    name: Node v${{ matrix.node }}
    steps:
      - name: Configure git line-breaks
        run: git config --global core.autocrlf false

      - name: Checkout Commit
        uses: actions/checkout@v1

      - name: Checkout Master
        run: git branch -f master origin/master

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: latest

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: pnpm install
        run: pnpm install --ignore-scripts

      - name: run tests
        run: pnpm test
