name: Windows

on:
  # Run on all PRs (regardless of base branch)
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  # Run on direct pushes to the default branch only (avoid duplicate runs for PR branches)
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    # Ensure only one run per PR/branch is active; cancel superseded runs on new pushes
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.head_ref || github.ref_name }}
      cancel-in-progress: true

    name: Validate (Windows)
    steps:
      - name: Configure git line-breaks
        run: git config --global core.autocrlf false

      - name: Checkout Commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout Master
        if: ${{ github.ref_name != 'master' }}
        run: git branch -f master origin/master

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.0

      - name: install pnpm
        run: npm install pnpm -g

      - name: pnpm install
        run: pnpm install --ignore-scripts

      - name: run tests
        run: pnpm test
