name: Validate

on:
  # Run on all PRs (regardless of base branch)
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  # Run on direct pushes to the default branch only (avoid duplicate runs for PR branches)
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    # Ensure only one run per PR/branch is active; cancel superseded runs on new pushes
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.head_ref || github.ref_name }}
      cancel-in-progress: true

    name: Validate

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 20

      - name: Checkout Master
        if: ${{ github.ref_name != 'master' }}
        run: |
          git fetch origin
          git branch -f master origin/master

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.0

      - name: Install pnpm
        run: npm install pnpm -g

      - name: Sanity Check
        run: |
          echo branch `git branch --show-current`;
          echo node `node --version`;
          echo yarn `pnpm --version`

      - name: pnpm install
        run: pnpm install

      - name: Audit Dependencies
        run: pnpm security

      - name: Build Packages
        run: pnpm --recursive build

      - name: Lint Repo
        run: pnpm lint:js

      - name: Run Tests
        run: pnpm ci:test
