name: Validate

on:
  pull_request:
    types:
      - edited
      - opened
      - synchronize
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - node: '20'
            pnpm: latest
          - node: '18'
            pnpm: latest
          - node: '16'
            pnpm: '8'

    name: Node v${{ matrix.node }}

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v1

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: ${{ matrix.pnpm }}

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Checkout Master
        run: git branch -f master origin/master

      - name: Sanity Check
        run: |
          echo branch `git branch --show-current`;
          echo node `node --version`;
          echo yarn `pnpm --version`

      - name: pnpm install
        run: pnpm install

      - name: Audit Dependencies
        run: pnpm security

      - name: Build Packages
        run: pnpm --recursive build

      - name: Lint Repo
        run: pnpm lint:js
        if: ${{ matrix.pnpm == 'latest' }}

      - name: Run Tests
        run: pnpm ci:coverage
